In [1]:
import numpy as np

In [3]:
arr = np.array([23, 45, 67, 89, 10])

In [5]:
print(arr)

[23 45 67 89 10]


In [7]:
arr

array([23, 45, 67, 89, 10])

In [9]:
type(arr)

numpy.ndarray

In [11]:
arr[2]

67

In [13]:
arr[2] = 100

In [15]:
arr

array([ 23,  45, 100,  89,  10])

In [21]:
arr1 = np.array([12, 34.98, 55, True, "Pune"])

In [23]:
arr1

array(['12', '34.98', '55', 'True', 'Pune'], dtype='<U32')

In [25]:
arr1.dtype

dtype('<U32')

In [27]:
arr

array([ 23,  45, 100,  89,  10])

In [29]:
arr * 2

array([ 46,  90, 200, 178,  20])

### check which one is faster.... list or array

In [32]:
import time

In [36]:
time.time()

1750657507.411978

In [39]:
s = 100000

list1 = list(range(s))

arr1 = np.array(list1)

In [41]:
# for list
start_time = time.time()
x = [i * 2 for i in list1]
time_list = time.time() - start_time
print("time taken by list:", time_list)

time taken by list: 0.009733200073242188


In [43]:
# for array
start_time = time.time()
y = arr1 * 2
time_arr = time.time() - start_time
print("time taken by list:", time_arr)

time taken by list: 0.0016121864318847656


In [45]:
time_list / time_arr

6.037267080745342

In [47]:
# arange

In [51]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [61]:
arr

array([ 23,  45, 100,  89,  10])

In [63]:
arr.ndim

1

In [65]:
# 2-d arrays

In [67]:
arr = np.array([[1, 2, 3], [4, 2, 5], [6, 9, 4], [6,3,8]])

In [69]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 8]])

In [71]:
arr.ndim

2

In [73]:
arr.size

12

In [75]:
arr.shape

(4, 3)

In [79]:
arr.flatten()

array([1, 2, 3, 4, 2, 5, 6, 9, 4, 6, 3, 8])

In [81]:
arr.flatten().ndim

1

In [83]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 8]])

In [85]:
arr.reshape(6, 2)

array([[1, 2],
       [3, 4],
       [2, 5],
       [6, 9],
       [4, 6],
       [3, 8]])

In [87]:
arr.reshape(2, 6)

array([[1, 2, 3, 4, 2, 5],
       [6, 9, 4, 6, 3, 8]])

In [89]:
arr.reshape(2, -1)

array([[1, 2, 3, 4, 2, 5],
       [6, 9, 4, 6, 3, 8]])

In [91]:
arr.reshape(3, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[2, 5],
        [6, 9]],

       [[4, 6],
        [3, 8]]])

In [93]:
# slicing

In [95]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 8]])

In [99]:
arr1 = np.arange(3, 13)
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [101]:
arr1[3:7]

array([6, 7, 8, 9])

In [103]:
arr[1:3, 0:2]

array([[4, 2],
       [6, 9]])

In [105]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 8]])

In [107]:
arr[1:3, :]

array([[4, 2, 5],
       [6, 9, 4]])

In [109]:
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
np.mean(arr1)

7.5

In [113]:
np.std(arr1)

2.8722813232690143

#### linear alg

In [116]:
a = np.array([[1,4], [4, 9]])
b = np.array([[3, 3], [10, 1]])

In [118]:
a

array([[1, 4],
       [4, 9]])

In [120]:
b

array([[ 3,  3],
       [10,  1]])

In [122]:
a @ b

array([[ 43,   7],
       [102,  21]])

In [124]:
np.dot(a, b)

array([[ 43,   7],
       [102,  21]])

In [126]:
a

array([[1, 4],
       [4, 9]])

In [128]:
np.linalg.det(a)

-6.999999999999999

In [130]:
np.linalg.inv(a)

array([[-1.28571429,  0.57142857],
       [ 0.57142857, -0.14285714]])

In [132]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.65685425, 10.65685425]), eigenvectors=array([[-0.92387953, -0.38268343],
       [ 0.38268343, -0.92387953]]))

In [134]:
# vector

vec = np.array([3, 6])

In [136]:
np.linalg.norm(vec)

6.708203932499369

In [140]:
help(np.linalg.norm)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix nor